services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_API_URL: /api
        VITE_STREAM_API_KEY: ${VITE_STREAM_API_KEY}
    ports:
      - "5173:80"
    depends_on:
      - backend

